# -*- coding: utf-8 -*-
"""Pandas_23.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ucQDkOiNkvvL08s6cGD9CuaBOcVnaO4A
"""

import pandas

df=pandas.read_csv('/content/sample_data/california_housing_test.csv') #read_csv function : To load CSV Data file.

print(df.head()) #Prints first 5 records

#to get the number of rows and columns
print(df.shape) #First value number of Rows and Second number is the number of columns

print(type(df))

print(df.shape()) #Shape is a attribute not a method
#This will cause an error.

print(df.columns) #get the column names

print(df.dtypes) #get the dtypes of each column

#get more information about data
print(df.info())

#if we want a specific column from data
median_income_df=df['median_income'] 
print(median_income_df.head()) #show the first 5 observations

print(median_income_df.tail()) #show the last 5 observation

subset=df[['population','households','median_income']]
print(subset.head())

print(subset.tail())

print(df.head())

print(df.loc[0]) #get the first row
#python counts from 0

#get the 100 row
print(df.loc[99])

df.tail(1)

print(df.loc[99])

df.head(1)

print(df.loc[-1])

#the label[-1] is not defined index

number_of_rows=df.shape[0] 
#use the first valuegiven from shape to get number of rows

print(number_of_rows)

last_row_index=number_of_rows-1 #subtract 1 from the value since we want the last index value

print(last_row_index)

print(df.loc[last_row_index])

print(df.tail(n=1)) #multiple ways to access the records

df.iloc[1]

df.iloc[-1]

subset_loc=df.loc[0]
print(type(subset_loc)) #type using loc of 1 row

#select the first,100th and 1000th rows

#note: double square brackets similar to the syntax used to subset multiple columns
print(df.loc[[0,99,999]])

print(df.iloc[[0,99,999]])

print(median_income_df.mean()) #arithmatic mean
print(median_income_df.min())
print(median_income_df.max())
print(median_income_df.std())
print(median_income_df.mode())
print(median_income_df.median())
#min,Max,and std are also methods in numpy .ndarray

scientists=pandas.read_csv("/content/scientists.csv")
print(scientists)

ages=scientists['Age']
print(ages)

#to get basic stats
print(ages.describe())

#what if you wanted to subset ages  by identifying those above the mean?

print(ages[ages>ages.mean()])

print(ages>ages.mean())

print(ages*ages)

print(ages+ages)

print(ages+100)

print(ages*2)

rev_ages1=ages.sort_index()
#rev_ages=ages.sort_index(ascending=False)
#print(rev_ages)
print(rev_ages1)

scientists.describe().T

#Transpose of the series

#Data Frame Info
scientists.info()

print(scientists[scientists['Age']<scientists['Age'].mean()])

firsthalf=scientists[:4]
secondhalf=scientists[4:]
firsthalf

secondhalf

secondhalf.rename(columns = {'Name':'NAME'}, inplace = True)

# After renaming the columns
print("\nAfter modifying first column:\n", secondhalf.columns)

secondhalf.columns = ['NAME', 'BORN', 'DIED','AGE','OCC']
secondhalf

#Rename column names using DataFrame set_axis() function

secondhalf.set_axis(['A', 'B', 'C','D','E'], axis='columns', inplace=True)
secondhalf

# Using DataFrame.insert() to add a column
secondhalf.insert(2, "Age", [21, 22, 24, 23], True)
secondhalf

df2 = secondhalf.assign(address=['Delhi', 'Bangalore', 'Chennai', 'Patna'])
df2